/// True for user text that a CLI injects (system reminders, environment
/// context, instructions, command wrappers) instead of text that a person
/// typed. This is sessport's list, shared by both readers.
pub(crate) fn is_synthetic_user_text(text: &str) -> bool {
    const PREFIXES: &[&str] = &[
        "<system-reminder>",
        "<environment_context>",
        "<user_instructions>",
        "<permissions instructions>",
        "# AGENTS.md instructions",
        "<command-name>",
        "<command-message>",
        "<local-command-stdout>",
        "<local-command-caveat>",
        "<session_context>",
        "<hook_context>",
        "Caveat: The messages below were generated by the user",
    ];
    let text = crate::js::trim_start(text);
    text.is_empty() || PREFIXES.iter().any(|p| text.starts_with(p))
}
